header = {'Cruise',	'Station','Type','mon/day/yr','hh:mm','Lon [°E]',...
    'Lat [°N]','Bot. Depth[m]','Bot. Depth [m]','Depth[m]','QF','Temperature[°C]',...
    'Salinity','Density','Oxygen[µM]','OxygenSat[%]','Nitrate[µM]',...
    'Chlorophyll[µg/l]','BackScatter[/m/sr]','pHinsitu[Total]','pH25C[Total]','CDOM[ppb]'};


%varname = {'cruiseid','station','type','mmddyy','hhmm','longtitude',...
%    'latitude','bottomDepth','depth','QF','temperature','salinity',...
%    'sigma','oxygen','oxygenSat','nitrate','chlorophyll','backscatter',...
%    'pHinsitu','ph25C'};

varname = {'crid','stn','type','mmddyy','hhmm','lon','lat','botDep','botDep','depth',...
    'QF','T','S','sigma','O2','O2sat','NO3','chlor','bbp','pHin','pH25','cdom'};

units = {'string','string','string','mm/dd/yy','HH:MM','deg east',...
    'deg north','m','m','m','flag','deg C','salinity','kg m^-3','microM','%',...
    'microM','micro g L^-1','m^-1 sr^-1','total@insitu','total@25C','ppb'};

format = {'%s','%d','%s','%s','%s','%f','%f','%f','%f','%f','%d','%f','%f',...
    '%f','%f','%f','%f','%f','%f','%f','%f','%f'};



head2var = containers.Map(header,varname);
var2units = containers.Map(varname,units);
head2units = containers.Map(header,units);
head2form = containers.Map(header,format);
